### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by kravi2018** [CVxTz/face_age_gender#1]
Traceback (most recent call last): File "/home/DSAdm/anaconda/envs/v36/lib/python3.6/site-packages/keras/utils/data_utils.py", line 685, in get inputs = self.queue.get(block=True).get() File "/home/DSAdmin/anaconda/envs/v36/lib/python3.6/multiprocessing/pool.py", line 644, in get raise self._value File "/home/DSAdmin/anaconda/envs/v36/lib/python3.6/multiprocessing/pool.py", line 119, in worker result = (True, func(*args, **kwds)) File "/home/DSAdmin/anaconda/envs/v36/lib/python3.6/site-packages/keras/utils/data_utils.py", line 626, in next_sample return six.next(_SHARED_SEQUENCES[uid]) ValueError: generator already executing

**Comment by CVxTz** [comment]
lol

**Comment by kravi2018** [comment]
@CVxTz I am very new to Tensorflow. Could you please help me?
